[package]
name = "test_transpiler"
version = "0.0.1"
edition = "2024"

[lib]

[dependencies]

[dev-dependencies]
nanorand = "0.7.0"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./doc_header.html"]
