[package]
name = "test_cnot_parity_matrix"
version = "0.0.1"
edition = "2024"

[dependencies]
bits.workspace = true
core.workspace = true
circuit.workspace = true
simulator.workspace = true
graph.workspace = true
openqasm2.workspace = true
rand.workspace = true

[dev-dependencies]
rand_chacha.workspace = true

[features]
default = []
