[package]
name = "test_cnot_parity_matrix"
version = "0.0.1"
edition = "2024"

[dependencies]
test_bits = { path = "../bits" }
test_core = { path = "../core" }
test_circuit = { path = "../circuit" }
test_simulator = { path = "../simulator" }
openqasm2 = { workspace = true, optional = true }
rand.workspace = true
rand_chacha.workspace = true

[features]
default = []
openqasm2 = ["dep:openqasm2", "test_circuit/openqasm2"]
